#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.10
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'arpwatch.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.10
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/arpwatch" ] ; then
	invoke-rc.d --skip-systemd-native arpwatch stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.10
dpkg-maintscript-helper rm_conffile /etc/arpwatch.conf 2.1a15-3\~ arpwatch -- "$@"
# End automatically added section
