#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    SEQFILE=/var/spool/cron/atjobs/.SEQ
    if [ ! -f $SEQFILE ]; then
	echo 0 > $SEQFILE
	chmod 600 $SEQFILE
	chown daemon:daemon $SEQFILE
    fi
fi

# Automatically added by dh_systemd_enable/13.10
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'atd.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'atd.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'atd.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'atd.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/13.10
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/atd" ]; then
		update-rc.d atd defaults 89 11 >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d atd $_dh_action || exit 1
	fi
fi
# End automatically added section

