#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.11.4
dpkg-maintscript-helper mv_conffile /etc/audisp/plugins.d/af_unix.conf /etc/audit/plugins.d/af_unix.conf 1:3.0\~alpha9-1\~ -- "$@"
dpkg-maintscript-helper mv_conffile /etc/audisp/plugins.d/syslog.conf /etc/audit/plugins.d/syslog.conf 1:3.0\~alpha9-1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/audisp/audispd.conf 1:3.0\~alpha9-1\~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.11.4
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/auditd" ] ; then
	chmod +x "/etc/init.d/auditd" >/dev/null || true
fi
# End automatically added section
