#!/bin/sh
# postinst script for kea-common
#
# see: dh_installdeb(1)

set -e

case "$1" in
    configure)
        addgroup --force-badname --system _kea >/dev/null || exit 1
        adduser --force-badname --quiet --system --home /var/lib/kea \
           --shell /bin/false --no-create-home --disabled-password --disabled-login \
           --gecos "Kea DHCP User" --group _kea >/dev/null || exit 1

        # From version 2.2.0-2 we leave the handling of the /var/log/kea and
        # /var/lib/kea directories to systemd (creation and ownership/permissions
        # settings). When upgrading from kea-common (< 2.2.0-2) drop the now
        # useless dpkg-statoverrides.
        if [ "$2" != "" ] && dpkg --compare-versions "$2" lt "2.2.0-2"; then
            for d in /var/log/kea /var/lib/kea; do
                if dpkg-statoverride --list $d >/dev/null 2>&1; then
                    dpkg-statoverride --remove $d
                fi
            done
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_apparmor/3.0.8-3
if [ "$1" = "configure" ]; then
    APP_PROFILE="/etc/apparmor.d/usr.sbin.kea-lfc"
    if [ -f "$APP_PROFILE" ]; then
        # Add the local/ include
        LOCAL_APP_PROFILE="/etc/apparmor.d/local/usr.sbin.kea-lfc"

        test -e "$LOCAL_APP_PROFILE" || {
            mkdir -p `dirname "$LOCAL_APP_PROFILE"`
            install --mode 644 /dev/null "$LOCAL_APP_PROFILE"
        }

        # Reload the profile, including any abstraction updates
        if aa-enabled --quiet 2>/dev/null; then
            apparmor_parser -r -T -W "$APP_PROFILE" || true
        fi
    fi
fi
# End automatically added section


exit 0
