#!/bin/sh
set -e
# Automatically added by dh_apparmor/3.0.8-3
if [ "$1" = "purge" ] && ! [ -e "/etc/apparmor.d/usr.sbin.kea-lfc" ] ; then
    rm -f "/etc/apparmor.d/disable/usr.sbin.kea-lfc" || true
    rm -f "/etc/apparmor.d/force-complain/usr.sbin.kea-lfc" || true
    rm -f "/etc/apparmor.d/local/usr.sbin.kea-lfc" || true
    rm -f /var/cache/apparmor/*/"usr.sbin.kea-lfc" || true
    rmdir /etc/apparmor.d/disable 2>/dev/null || true
    rmdir /etc/apparmor.d/local   2>/dev/null || true
    rmdir /etc/apparmor.d         2>/dev/null || true
fi
# End automatically added section
