#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.4
if [ "$1" = "remove" ] && [ -x "/etc/init.d/lcdproc" ] ; then
	chmod -x "/etc/init.d/lcdproc" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d lcdproc remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.11.4
dpkg-maintscript-helper mv_conffile /etc/init.d/LCDd /etc/init.d/lcdproc 0.5.9-5\~ lcdproc -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'lcdproc.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.11.4
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section
# Automatically added by dh_cme_upgrade/UNDECLARED
# Purge configuration files handled by cme

if [ "$1" = purge ]
then
    echo "Purging cme files: '/etc/LCDd.conf*'"
    rm -rf /etc/LCDd.conf*
fi
# End automatically added section
