#!/bin/sh

set -e

# Automatically added by dh_installinit/13.11.4
if [ "$1" = "remove" ] && [ -x "/etc/init.d/lldpd" ] ; then
	chmod -x "/etc/init.d/lldpd" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d lldpd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'lldpd.service' >/dev/null || true
	fi
fi
# End automatically added section


case "$1" in
    purge)
	dpkg-statoverride --remove /usr/sbin/lldpcli
	dpkg-statoverride --quiet --remove /usr/sbin/lldpctl || true
        deluser --system _lldpd || true
        delgroup --system _lldpd || true

        rm -rf /run/lldpd
    ;;
    *)
    ;;
esac

exit 0
