#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.4
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/mdadm-waitidle" ] ; then
	chmod +x "/etc/init.d/mdadm-waitidle" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.11.4
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/mdadm" ] ; then
	chmod +x "/etc/init.d/mdadm" >/dev/null || true
fi
# End automatically added section
