#!/bin/sh
set -e

case "$1" in
    remove|purge)
        # remove chroot/socket directory upon removal
        rm -rf /var/lib/ocserv/run
        ;;
    *)
        ;;
esac

# Automatically added by dh_installinit/13.11.4
if [ "$1" = "remove" ] && [ -x "/etc/init.d/ocserv" ] ; then
	chmod -x "/etc/init.d/ocserv" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d ocserv remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'ocserv.service' >/dev/null || true
	fi
fi
# End automatically added section


