#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.1~bpo11+1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/salt-minion" ] ; then
	chmod -x "/etc/init.d/salt-minion" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d salt-minion remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_enable/13.11.1~bpo11+1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'salt-minion.service' >/dev/null || true
	fi
fi
# End automatically added section
