[Unit]
StartLimitIntervalSec=0
ConditionPathExists=/run/chrony/chrony.conf
After=vyos-router.service

[Service]
EnvironmentFile=
ExecStart=
ExecStart=!/usr/sbin/chronyd -F 1 -f /run/chrony/chrony.conf
PIDFile=
PIDFile=/run/chrony/chrony.pid
Restart=always
RestartSec=10
# Required for VRF support
ProcSubset=all
ProtectControlGroups=no