#!/usr/sbin/nft -f


delete table ip vyos_conntrack
table ip vyos_conntrack {
    chain VYOS_CT_IGNORE {
         return
    }
    chain VYOS_CT_TIMEOUT {
        return
    }


    chain PREROUTING {
        type filter hook prerouting priority -300; policy accept;
        counter jump VYOS_CT_IGNORE
        counter jump VYOS_CT_TIMEOUT
        counter jump FW_CONNTRACK
        counter jump NAT_CONNTRACK
        counter jump WLB_CONNTRACK
        notrack
    }

    chain PREROUTING_HELPER {
        type filter hook prerouting priority -5; policy accept;
        counter jump VYOS_CT_HELPER
    }

    chain OUTPUT {
        type filter hook output priority -300; policy accept;
        counter jump VYOS_CT_IGNORE
        counter jump VYOS_CT_TIMEOUT
        counter jump FW_CONNTRACK
        counter jump NAT_CONNTRACK
        notrack
    }

    chain OUTPUT_HELPER {
        type filter hook output priority -5; policy accept;
        counter jump VYOS_CT_HELPER
    }









    chain VYOS_CT_HELPER {
        return
    }


    chain FW_CONNTRACK {
        accept
    }

    chain NAT_CONNTRACK {
        return
    }

    chain WLB_CONNTRACK {
        return
    }

}

delete table ip6 vyos_conntrack
table ip6 vyos_conntrack {
    chain VYOS_CT_IGNORE {
        return
    }
    chain VYOS_CT_TIMEOUT {
        return
    }


    chain PREROUTING {
        type filter hook prerouting priority -300; policy accept;
        counter jump VYOS_CT_IGNORE
        counter jump VYOS_CT_TIMEOUT
        counter jump FW_CONNTRACK
        counter jump NAT_CONNTRACK
        notrack
    }

    chain PREROUTING_HELPER {
        type filter hook prerouting priority -5; policy accept;
        counter jump VYOS_CT_HELPER
    }

    chain OUTPUT {
        type filter hook output priority -300; policy accept;
        counter jump VYOS_CT_IGNORE
        counter jump VYOS_CT_TIMEOUT
        counter jump FW_CONNTRACK
        counter jump NAT_CONNTRACK
        notrack
    }

    chain OUTPUT_HELPER {
        type filter hook output priority -5; policy accept;
        counter jump VYOS_CT_HELPER
    }









    chain VYOS_CT_HELPER {
        return
    }


    chain FW_CONNTRACK {
        accept
    }

    chain NAT_CONNTRACK {
        return
    }

}