#!/usr/sbin/nft -f


flush chain raw vyos_global_rpfilter
flush chain ip6 raw vyos_global_rpfilter

table raw {
    chain vyos_global_rpfilter {
        return
    }
}

table ip6 raw {
    chain vyos_global_rpfilter {
        return
    }
}

table ip vyos_filter {

    chain VYOS_FORWARD_filter {
        type filter hook forward priority filter; policy accept;
        jump VYOS_STATE_POLICY
        ct state {established,related} counter accept comment "ipv4-FWD-filter-5"
        ct state {invalid} counter jump NAME_CONN_FILTER comment "ipv4-FWD-filter-10"
        counter accept comment "FWD-filter default-action accept"
    }

    chain VYOS_INPUT_filter {
        type filter hook input priority filter; policy accept;
        jump VYOS_STATE_POLICY
        ct state {established,related} counter accept comment "ipv4-INP-filter-5"
        ct state {invalid} counter jump NAME_CONN_FILTER comment "ipv4-INP-filter-10"
        meta l4proto  tcp tcp dport {22} counter jump NAME_PHANTOM_MANAGEMENT comment "ipv4-INP-filter-20"
        counter accept comment "INP-filter default-action accept"
    }

    chain VYOS_OUTPUT_raw {
        type filter hook output priority raw; policy accept;
        counter accept comment "OUT-raw default-action accept"
    }
    chain VYOS_OUTPUT_filter {
        type filter hook output priority filter; policy accept;
        jump VYOS_STATE_POLICY
        counter accept comment "OUT-filter default-action accept"
    }

    chain VYOS_PREROUTING_raw {
        type filter hook prerouting priority raw; policy accept;
        counter accept comment "PRE-raw default-action accept"
    }

    chain VYOS_FRAG_MARK {
        type filter hook prerouting priority -450; policy accept;
        ip frag-off & 0x3fff != 0 meta mark set 0xffff1 return
    }

    chain NAME_CONN_FILTER {
        ct state {established,related} counter accept comment "ipv4-NAM-CONN_FILTER-10"
        ct state {invalid} counter drop comment "ipv4-NAM-CONN_FILTER-20"
        counter return comment "CONN_FILTER default-action return"
    }
    chain NAME_PHANTOM_MANAGEMENT {
        counter return comment "PHANTOM_MANAGEMENT default-action return"
    }



    chain VYOS_STATE_POLICY {
        ct state established counter accept
        ct state invalid counter drop
        ct state related counter accept
        return
    }
}

table ip6 vyos_filter {

    chain VYOS_IPV6_FORWARD_filter {
        type filter hook forward priority filter; policy accept;
        jump VYOS_STATE_POLICY6
        counter accept comment "FWD-filter default-action accept"
    }

    chain VYOS_IPV6_INPUT_filter {
        type filter hook input priority filter; policy accept;
        jump VYOS_STATE_POLICY6
        counter accept comment "INP-filter default-action accept"
    }

    chain VYOS_IPV6_OUTPUT_raw {
        type filter hook output priority raw; policy accept;
        counter accept comment "OUT-raw default-action accept"
    }
    chain VYOS_IPV6_OUTPUT_filter {
        type filter hook output priority filter; policy accept;
        jump VYOS_STATE_POLICY6
        counter accept comment "OUT-filter default-action accept"
    }

    chain VYOS_IPV6_PREROUTING_raw {
        type filter hook prerouting priority raw; policy accept;
        counter accept comment "PRE-raw default-action accept"
    }
    chain VYOS_FRAG6_MARK {
        type filter hook prerouting priority -450; policy accept;
        exthdr frag exists meta mark set 0xffff1 return
    }



    chain VYOS_STATE_POLICY6 {
        ct state established counter accept
        ct state invalid counter drop
        ct state related counter accept
        return
    }
}

## Bridge Firewall
table bridge vyos_filter {
    chain VYOS_FORWARD_filter {
        type filter hook forward priority filter; policy accept;
    counter accept comment "FWD-filter default-action accept"
    }




}