#!/bin/sh
set -e
if [ "$1" = purge ]
then
	rm -rf /var/spool/cron/atjobs /var/spool/cron/atspool
fi

# Automatically added by dh_installinit/13.10
if [ "$1" = "remove" ] && [ -x "/etc/init.d/atd" ] ; then
	chmod -x "/etc/init.d/atd" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d atd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_enable/13.10
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'atd.service' >/dev/null || true
	fi
fi
# End automatically added section

