#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.11.4
dpkg-maintscript-helper rm_conffile /etc/logrotate.d/psaccs_atop -- "$@"
dpkg-maintscript-helper rm_conffile /etc/logrotate.d/psaccu_atop -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.11.4
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/atopacct" ] ; then
	chmod +x "/etc/init.d/atopacct" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.11.4
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/atop" ] ; then
	chmod +x "/etc/init.d/atop" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'atop-rotate.service' >/dev/null || true
fi
# End automatically added section
