#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.11.4
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'atop-rotate.timer' 'atop.service' 'atopacct.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.11.4
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/atop" ] ; then
	invoke-rc.d --skip-systemd-native atop stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installinit/13.11.4
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/atopacct" ] ; then
	invoke-rc.d --skip-systemd-native atopacct stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.11.4
dpkg-maintscript-helper rm_conffile /etc/logrotate.d/psaccs_atop -- "$@"
dpkg-maintscript-helper rm_conffile /etc/logrotate.d/psaccu_atop -- "$@"
# End automatically added section
