#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    if [ -d /run/systemd/system ]; then
        if [ -z "$2" ]; then
            # On initial install make sure udev notifies systemd
            udevadm trigger || true
        else
            # On upgrade make sure running daemons are restarted
            systemctl try-restart hv-fcopy-daemon.service hv-kvp-daemon.service hv-vss-daemon.service
        fi
    fi
fi

# Automatically added by dh_installdeb/13.11.4
dpkg-maintscript-helper mv_conffile /etc/init.d/hyperv-daemons.hv-fcopy-daemon /etc/init.d/hv-fcopy-daemon 5.8\~rc7-1\~exp1 -- "$@"
dpkg-maintscript-helper mv_conffile /etc/init.d/hyperv-daemons.hv-kvp-daemon /etc/init.d/hv-kvp-daemon 5.8\~rc7-1\~exp1 -- "$@"
dpkg-maintscript-helper mv_conffile /etc/init.d/hyperv-daemons.hv-vss-daemon /etc/init.d/hv-vss-daemon 5.8\~rc7-1\~exp1 -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'hv-fcopy-daemon.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'hv-fcopy-daemon.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'hv-fcopy-daemon.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'hv-fcopy-daemon.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'hv-fcopy-daemon.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/hv-fcopy-daemon" ]; then
		update-rc.d hv-fcopy-daemon defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native hv-fcopy-daemon $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'hv-kvp-daemon.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'hv-kvp-daemon.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'hv-kvp-daemon.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'hv-kvp-daemon.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'hv-kvp-daemon.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/hv-kvp-daemon" ]; then
		update-rc.d hv-kvp-daemon defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native hv-kvp-daemon $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'hv-vss-daemon.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'hv-vss-daemon.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'hv-vss-daemon.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'hv-vss-daemon.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'hv-vss-daemon.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/hv-vss-daemon" ]; then
		update-rc.d hv-vss-daemon defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native hv-vss-daemon $_dh_action || exit 1
	fi
fi
# End automatically added section


exit 0
