#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.4
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/hv-vss-daemon" ] ; then
	invoke-rc.d --skip-systemd-native hv-vss-daemon stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installinit/13.11.4
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/hv-kvp-daemon" ] ; then
	invoke-rc.d --skip-systemd-native hv-kvp-daemon stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installinit/13.11.4
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/hv-fcopy-daemon" ] ; then
	invoke-rc.d --skip-systemd-native hv-fcopy-daemon stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.11.4
dpkg-maintscript-helper mv_conffile /etc/init.d/hyperv-daemons.hv-fcopy-daemon /etc/init.d/hv-fcopy-daemon 5.8\~rc7-1\~exp1 -- "$@"
dpkg-maintscript-helper mv_conffile /etc/init.d/hyperv-daemons.hv-kvp-daemon /etc/init.d/hv-kvp-daemon 5.8\~rc7-1\~exp1 -- "$@"
dpkg-maintscript-helper mv_conffile /etc/init.d/hyperv-daemons.hv-vss-daemon /etc/init.d/hv-vss-daemon 5.8\~rc7-1\~exp1 -- "$@"
# End automatically added section
