#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.4
if [ "$1" = "remove" ] && [ -x "/etc/init.d/kea-dhcp-ddns-server" ] ; then
	chmod -x "/etc/init.d/kea-dhcp-ddns-server" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d kea-dhcp-ddns-server remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'kea-dhcp-ddns-server.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_apparmor/3.0.8-3
if [ "$1" = "purge" ] && ! [ -e "/etc/apparmor.d/usr.sbin.kea-dhcp-ddns" ] ; then
    rm -f "/etc/apparmor.d/disable/usr.sbin.kea-dhcp-ddns" || true
    rm -f "/etc/apparmor.d/force-complain/usr.sbin.kea-dhcp-ddns" || true
    rm -f "/etc/apparmor.d/local/usr.sbin.kea-dhcp-ddns" || true
    rm -f /var/cache/apparmor/*/"usr.sbin.kea-dhcp-ddns" || true
    rmdir /etc/apparmor.d/disable 2>/dev/null || true
    rmdir /etc/apparmor.d/local   2>/dev/null || true
    rmdir /etc/apparmor.d         2>/dev/null || true
fi
# End automatically added section
