#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.11.4
dpkg-maintscript-helper mv_conffile /etc/init.d/LCDd /etc/init.d/lcdproc 0.5.9-5\~ lcdproc -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.11.4
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/lcdproc" ] ; then
	chmod +x "/etc/init.d/lcdproc" >/dev/null || true
fi
# End automatically added section
