#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.11.4
dpkg-maintscript-helper rm_conffile /etc/tmpfiles.d/openvpn.conf 2.4.3-3\~ openvpn -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.11.4
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/openvpn" ] ; then
	chmod +x "/etc/init.d/openvpn" >/dev/null || true
fi
# End automatically added section
