#!/bin/sh
set -e
# Automatically added by dh_installinit/13.3.4
if [ -x "/etc/init.d/xe-guest-utilities" ] && [ "$1" = remove ]; then
	invoke-rc.d xe-guest-utilities stop || exit 1
fi
# End automatically added section
# Automatically added by dh_systemd_start/13.3.4
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'proc-xen.mount' 'xe-guest-utilities.service' >/dev/null || true
fi
# End automatically added section
