#!/bin/sh

set -e

case "$1" in
    purge)
        rm -fr /etc/zabbix/zabbix_agentd2.d
        rm -f  /etc/zabbix/zabbix_agent2.conf
        rm -f  /var/log/zabbix/zabbix_agent2.log*
    ;;
esac

# Automatically added by dh_installinit/13.11.4
if [ "$1" = "remove" ] && [ -x "/etc/init.d/zabbix-agent2" ] ; then
	chmod -x "/etc/init.d/zabbix-agent2" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d zabbix-agent2 remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'zabbix-agent2.service' >/dev/null || true
	fi
fi
# End automatically added section

